### ISSUE TITLE
SqlException on application restart

### ISSUE THREAD

**Issue by MMR-19** [tomasfabian/Joker#26]
I am using SqlTableDependency.Extensions on a .NET Framework 4.8 web MVC application.
I am using a SqlTableDependencyProvider with a lifetime UniqueScope (with a fixed FarServiceUniqueName).

On application restart, the new SqlTableDependencyProvider causes an SQL Exception: "There is already an object named 'dbo_MyTable_MyProjet/StartMessage/Insert' in the database. This causes a crash on my app, since I am doing these dependencies on Application_Start().

Shouldn't the Provider check for these objects in the database, and reuse them?
("If the application was closed without cleaning the conversation, it will be reused upon app restart")

**Comment by tomasfabian** [comment]
Hi @MMR-19,
I have to review the description of each `LifetimeScope`. Could you try out the `ApplicationScope` that should be the most "bullet proof", please?

Thanks.

**Comment by tomasfabian** [comment]
The other option is that something went wrong with the fixed FarServiceUniqueName. Have you been using the `SqlTableDependencyProvider` without any problems before, please?

**Comment by MMR-19** [comment]
As of now I am using ApplicationScope. On app restart new triggers and objects are created, but after 3 minutes (WatchDog timeout) the old ones are deleted. Which seems to be the correct behaviour!

However it is quite hard to replicate the problem caused by Christians original development that blocks my tables operations...

I will keep the system running and can update you if any errors happen!

**Comment by MMR-19** [comment]
About the FarServiceUniqueName, I believe the problem was resolved, because all the object had the correct name. However using the UniqueScope, on app restart the SqlException was triggered.

I was not using SqlTableDependencyProvider before. Only tried with UniqueScope, until the SqlException. Currently using ApplicationScope, even though it is not ideal.

**Comment by tomasfabian** [comment]
Sorry we were discussing this issue in 2 different threads. So is the end result of the above error that the trigger and DB objects were not eliminated, causing a "lock" on those table again as with the original `SqlTableDependency`, please?

Maybe is it some kind of edge case that is still not taken into account?

**Comment by MMR-19** [comment]
I believe what happened was:
1) Using the web app with UniqueScope and FarServiceUniqueName
2) Somehow the DB objects got "stuck" (something is happening with these objects that are not deleted automatically and block the DB)
3) On App restart I get this SqlException, because the TableProvider cannot rewrite/reuse the old objects because they are stuck
4) After some time the stuck objects cause the table to be blocked and nothing can be inserted again

I actually believe that this SqlException is a consequence of the objects being stuck, but I am not sure...
I believe this, because some manual restarts on the app worked fine! Even using UniqueScope...

**Comment by tomasfabian** [comment]
This issue haven't been seen for few months so it is very likely that it is caused by the new `FarServiceUniqueName`. What especially bothered me (I just recalled it) that there is a design flow IMO in the very base `TableDependency` class that uses a virtual method call in its constructor. 

The way how I tried to overcome it is [visible here](https://github.com/tomasfabian/Joker/blob/master/SqlTableDependency.Extensions/SqlTableDependencyWithReconnection.cs#L61).


```C#
    protected TableDependency(
      string connectionString,
      string tableName = null,
      string schemaName = null,
      IModelToTableMapper<T> mapper = null,
      IUpdateOfModel<T> updateOf = null,
      ITableDependencyFilter filter = null,
      DmlTriggerType dmlTriggerType = DmlTriggerType.All,
      bool executeUserPermissionCheck = true)
    {
      //...
      // virtual member call in ctor
      this._dataBaseObjectsNamingConvention = this.GetBaseObjectsNamingConvention();
    }
```

```C#
   SqlTableDependencyWithReconnection //...
      : base(connectionString, tableName, schemaName, mapper, updateOf, filter, notifyOn, executeUserPermissionCheck, includeOldValues)
    {
      //THIS IS TOO LATE IMO!
      Settings = settings;

      _dataBaseObjectsNamingConvention = GetBaseObjectsNamingConvention();
    }
```

The base constructors don't have access to the `Settings` property that is used in the following manner:
```C#
    public virtual string UniqueName
    {
      get
      {
        if (string.IsNullOrEmpty(Settings?.FarServiceUniqueName))
          return Environment.MachineName;

        return Settings.FarServiceUniqueName;
      }
    }
```

And Christian's `SqlTableDependency` also does dependent stuff in his constructor.

What do you think about the above assumptions @MMR-19?

**Comment by tomasfabian** [comment]
It's unfortunate that despite no reports for several months, it seemed like the issue had been resolved. Currently, I'm no longer using  `SqlTableDependency`. In general, I'm quite overwhelmed, therefore I'm considering archiving this repository and deprecating the NuGet package. I tried to do my best, however, the original bug from https://github.com/christiandelbianco/monitor-table-change-with-sqltabledependency is both critical and challenging to reproduce, making it difficult to find a solution. :(
Personally, I would like to recommend a more decoupled approach by utilizing Change Data Capture or a similar mechanism.

Regards Tomas.

**Comment by MMR-19** [comment]
These past few days, ApplicationScope seems to work without any problems... But yes the issue is quite difficult to reproduce

**Comment by MMR-19** [comment]
Been running my application for a few months, and ApplicationScope is still going strong, without "stuck" tables!
